id: PYSEC-0000-CVE-2023-40570
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
details: Datasette is an open source multi-tool for exploring and publishing data.
  This bug affects Datasette instances running a Datasette 1.0 alpha - 1.0a0, 1.0a1,
  1.0a2 or 1.0a3 - in an online accessible location but with authentication enabled
  using a plugin such as datasette-auth-passwords. The `/-/api` API explorer endpoint
  could reveal the names of both databases and tables - but not their contents - to
  an unauthenticated user. Datasette 1.0a4 has a fix for this issue. This will block
  access to the API explorer but will still allow access to the Datasette read or
  write JSON APIs, as those use different URL patterns within the Datasette `/database`
  hierarchy. This issue is patched in version 1.0a4.
affected:
- package:
    name: datasette
    ecosystem: PyPI
    purl: pkg:pypi/datasette
  ranges:
  - type: GIT
    repo: https://github.com/simonw/datasette
    events:
    - introduced: "0"
    - fixed: 01e0558825b8f7ec17d3b691aa072daf122fcc74
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: ADVISORY
  url: https://github.com/simonw/datasette/security/advisories/GHSA-7ch3-7pp7-7cpq
- type: FIX
  url: https://github.com/simonw/datasette/commit/01e0558825b8f7ec17d3b691aa072daf122fcc74
aliases:
- CVE-2023-40570
- GHSA-7ch3-7pp7-7cpq
modified: "2023-08-31T13:50:00Z"
published: "2023-08-25T01:15:00Z"
