id: PYSEC-0000-CVE-2023-41164
details: In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri()
  is subject to a potential DoS (denial of service) attack via certain inputs with
  a very large number of Unicode characters.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "3.2"
    - fixed: 3.2.21
    - introduced: "4.1"
    - fixed: 4.1.11
    - introduced: "4.2"
    - fixed: 4.2.5
references:
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2023/sep/04/security-releases/
- type: WEB
  url: https://docs.djangoproject.com/en/4.2/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#!forum/django-announce
aliases:
- CVE-2023-41164
modified: "2023-11-03T05:15:00Z"
published: "2023-11-03T05:15:00Z"
