id: PYSEC-0000-CVE-2024-39329
details: An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14.
  The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote
  attackers to enumerate users via a timing attack involving login requests for users
  with an unusable password.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "5.0"
    - fixed: 5.0.7
    - introduced: "4.2"
    - fixed: 4.2.14
references:
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#%21forum/django-announce
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2024/jul/09/security-releases/
aliases:
- CVE-2024-39329
modified: "2024-07-10T05:15:00Z"
published: "2024-07-10T05:15:00Z"
