id: PYSEC-0000-CVE-2024-38875
details: An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7.
  urlize and urlizetrunc were subject to a potential denial of service attack via
  certain inputs with a very large number of brackets.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "4.2"
    - fixed: 4.2.14
    - introduced: "5.0"
    - fixed: 5.0.7
references:
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#%21forum/django-announce
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2024/jul/09/security-releases/
aliases:
- CVE-2024-38875
modified: "2024-07-10T05:15:00Z"
published: "2024-07-10T05:15:00Z"
