id: PYSEC-0000-CVE-2023-26150
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
details: "Versions of the package asyncua before 0.9.96 are vulnerable to Improper
  Authentication such that it is possible to access Address Space without encryption
  and authentication.\r\r**Note:**\r\rThis issue is a result of missing checks for
  services that require an active session."
affected:
- package:
    name: asyncua
    ecosystem: PyPI
    purl: pkg:pypi/asyncua
  ranges:
  - type: GIT
    repo: https://github.com/FreeOpcUa/opcua-asyncio
    events:
    - introduced: "0"
    - fixed: b4106dfd5037423c9d1810b48a97296b59cde513
    - fixed: 2be7ce80df05de8d6c6ae1ebce6fa2bb7147844a
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.9.96
references:
- type: FIX
  url: https://github.com/FreeOpcUa/opcua-asyncio/commit/b4106dfd5037423c9d1810b48a97296b59cde513
- type: FIX
  url: https://github.com/FreeOpcUa/opcua-asyncio/commit/2be7ce80df05de8d6c6ae1ebce6fa2bb7147844a
- type: WEB
  url: https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96
- type: EVIDENCE
  url: https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673435
- type: FIX
  url: https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673435
- type: WEB
  url: https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673435
- type: EVIDENCE
  url: https://gist.github.com/artfire52/84f7279a4119d6f90381ac49d7121121
- type: WEB
  url: https://gist.github.com/artfire52/84f7279a4119d6f90381ac49d7121121
- type: EVIDENCE
  url: https://github.com/FreeOpcUa/opcua-asyncio/issues/1014
- type: REPORT
  url: https://github.com/FreeOpcUa/opcua-asyncio/issues/1014
- type: FIX
  url: https://github.com/FreeOpcUa/opcua-asyncio/pull/1015
aliases:
- CVE-2023-26150
modified: "2023-10-04T17:12:00Z"
published: "2023-10-03T05:15:00Z"
